- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer
    mode: 0755

- name: Install Composer
  command: >
    php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer
